# Validate all YAML changes, e.g. http://lint.travis-ci.org/

dist: xenial
language: python
cache: pip
python:
  - pypy3
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install:
  - pip install --upgrade pytest # needed for cases where there is already an old pytest installed
  - pip install pytest-cov       # needed for the codecov uploader
  - pip install -r requirements.txt -r tests/requirements.txt
script:
  # Do not perform flake8 checks in pypy environments (see issue #146)
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pytest -o 'flake8-ignore=*.py ALL'; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pytest; fi
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d591e73173ccf74fe8ba
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
